#!/usr/bin/env bash

bin=/usr/local/bin

. "${bin}/functions.sh"
. "${bin}/source-env-file"

group_id=${ZDI_USER_GROUP_ID}
user_id=${ZDI_USER_ID}
dir_web=${ZDI_DIR_WEB}
dir_web_app=${ZDI_DIR_WEB_APP}

if command -v sudo >/dev/null 2>&1; then
    cmd=sudo
    if [ $EUID -eq 0 ]; then
        cmd=
    fi
else
    cmd=
    if [ $EUID -ne 0 ]; then
        show_warning 'Sudo does not exist! Commands will be executed by simple user.'
    fi
fi

show_info "Restoring permissions in web directory '${dir_web_app}'."

${cmd} reas "${dir_web}" 750 640
${cmd} chmod 750 "${dir_web}"
${cmd} chown -R "${user_id}":"${group_id}" "${dir_web}"

if [[ -f "${dir_web_app}/artisan" ]]
then
    ${cmd} reas "${dir_web_app}/storage" 770 660
    ${cmd} reas "${dir_web_app}/bootstrap/cache" 770 660
fi

while IFS= read -r -d '' bin_dir
do
    echo "${bin_dir}"
    ${cmd} chmod -R 750 "${bin_dir}"
done <   <(find "${dir_web_app}" -type d -name 'bin' -print0)

#
# Last line
#
# Add SETGID set-group-ID bit to folders to force parent group for new files and folders.
#
find "${dir_web}" -type d -print0 | xargs -0 chmod g+s

show_success 'Permissions restored!'
