#!/usr/bin/env bash

set -e

bin=/usr/local/bin

. "${bin}/functions.sh"

file="/home/.env"

if [ ! -e "${file}" ]; then
    show_warning "Environment file '${file}' does not exist.";
else
    # shellcheck disable=SC1090
    source "${file}"
fi
