services:

    kanboard-nginx:
        image: zablose/kanboard-nginx:1.27
        build:
            context: ./
            dockerfile: files/nginx.df
            args:
                - ARG_ENV=${ZDI_ENV}
                - ARG_PHP_FPM_HOST=${ZDI_PHP_FPM_HOST}
                - ARG_USER_GROUP_ID=${ZDI_USER_GROUP_ID}
                - ARG_USER_GROUP_NAME=${ZDI_USER_GROUP_NAME}
                - ARG_USER_ID=${ZDI_USER_ID}
                - ARG_USER_NAME=${ZDI_USER_NAME}
                - ARG_WEB_DOMAIN=${ZDI_WEB_DOMAIN}
                - ARG_WEB_ROOT_DIR=${ZDI_WEB_ROOT_DIR}
        container_name: kanboard-nginx
        env_file:
            -   path: ./examples/kanboard/.nginx.env
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./examples/kanboard/.nginx.env:/home/${ZDI_USER_NAME}/.env
            - kanboard_web:${ZDI_WEB_ROOT_DIR}/
            - kanboard_data:${ZDI_WEB_ROOT_DIR}/data/
            - kanboard_plugins:${ZDI_WEB_ROOT_DIR}/plugins/
        logging:
            driver: syslog
            options:
                syslog-address: 'tcp://127.0.0.1:514'
                tag: 'docker/kanboard-nginx'
        depends_on:
            - kanboard-php-fpm
            - kanboard-rsyslog

    kanboard-php-fpm:
        image: zablose/kanboard-php-fpm:${ZDI_VERSION_PHP}
        build:
            context: ./
            dockerfile: files/php-fpm.df
            args:
                - ARG_ENV=${ZDI_ENV}
                - ARG_USER_GROUP_ID=${ZDI_USER_GROUP_ID}
                - ARG_USER_GROUP_NAME=${ZDI_USER_GROUP_NAME}
                - ARG_USER_ID=${ZDI_USER_ID}
                - ARG_USER_NAME=${ZDI_USER_NAME}
                - ARG_WEB_ROOT_DIR=${ZDI_WEB_ROOT_DIR}
        container_name: kanboard-php-fpm
        env_file:
            -   path: ./examples/kanboard/.php-fpm.env
        environment:
            DATA_DIR: ${ZDI_WEB_ROOT_DIR}/data
            PLUGINS_DIR: ${ZDI_WEB_ROOT_DIR}/plugins
            DB_HOSTNAME: kanboard-mariadb
            DB_DRIVER: mysql
            DB_NAME: ${ZDI_DB_NAME}
            DB_USERNAME: ${ZDI_DB_USERNAME}
            DB_PASSWORD: ${ZDI_DB_PASSWORD}
        volumes:
            - ./examples/kanboard/.php-fpm.env:/home/${ZDI_USER_NAME}/.env
            - $HOME/.composer/cache/:/home/${ZDI_USER_NAME}/.composer/cache/
            - kanboard_web:${ZDI_WEB_ROOT_DIR}/
            - kanboard_data:${ZDI_WEB_ROOT_DIR}/data/
            - kanboard_plugins:${ZDI_WEB_ROOT_DIR}/plugins/
            - ./post-setup.kanboard.example.sh:/home/${ZDI_USER_NAME}/post-setup.sh
        logging:
            driver: syslog
            options:
                syslog-address: 'tcp://127.0.0.1:514'
                tag: 'docker/kanboard-php-fpm'
        depends_on:
            - kanboard-mariadb
            - kanboard-rsyslog

    kanboard-mariadb:
        image: mariadb:11.5.2
        container_name: kanboard-mariadb
        env_file:
            -   path: ./examples/kanboard/.php-fpm.env
        environment:
            MYSQL_ROOT_PASSWORD: ${ZDI_DB_PASSWORD}
            MYSQL_DATABASE: ${ZDI_DB_NAME}
            MYSQL_USER: ${ZDI_DB_USERNAME}
            MYSQL_PASSWORD: ${ZDI_DB_PASSWORD}
        logging:
            driver: syslog
            options:
                syslog-address: 'tcp://127.0.0.1:514'
                tag: 'docker/kanboard-mariadb'
        volumes:
            - kanboard_db:/var/lib/mysql/
            - ./db/mariadb/init/:/docker-entrypoint-initdb.d/
        depends_on:
            - kanboard-rsyslog

    kanboard-rsyslog:
        image: zablose/rsyslog:3.19.1
        build:
            context: ./
            dockerfile: files/rsyslog.df
        container_name: kanboard-rsyslog
        ports:
            - '514:514'
        volumes:
            - ./logs/:/var/log/

volumes:
    kanboard_data:
    kanboard_plugins:
    kanboard_web:
    kanboard_db:
