services:

    kanboard-nginx:
        image: zablose/nginx:1.27
        build:
            context: ./../../
            dockerfile: files/nginx.df
            args:
                - ARG_ENV=${ZDI_ENV}
                - ARG_TIMEZONE=${ZDI_TIMEZONE}
                - ARG_USER_GROUP_ID=${ZDI_USER_GROUP_ID}
                - ARG_USER_GROUP_NAME=${ZDI_USER_GROUP_NAME}
                - ARG_USER_ID=${ZDI_USER_ID}
                - ARG_USER_NAME=${ZDI_USER_NAME}
                - ARG_WEB_DOMAIN=${ZDI_WEB_DOMAIN}
                - ARG_WEB_ROOT_DIR=${ZDI_WEB_ROOT_DIR}
        container_name: kanboard-nginx
        environment:
            ZDI_CONTAINER_NAME: kanboard-nginx
            ZDI_PHP_FPM_HOST: kanboard-php-fpm
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./.env:/home/${ZDI_USER_NAME}/.env
            - kanboard_web:${ZDI_WEB_ROOT_DIR}/
            - ./app/data/:${ZDI_WEB_ROOT_DIR}/data/
            - ./app/plugins/:${ZDI_WEB_ROOT_DIR}/plugins/
            - ./setup/nginx.sh:/home/${ZDI_USER_NAME}/post-setup.sh
        logging:
            driver: syslog
            options:
                syslog-address: 'tcp://127.0.0.1:514'
                tag: 'docker/kanboard-nginx'
        depends_on:
            - kanboard-php-fpm
            - kanboard-rsyslog

    kanboard-php-fpm:
        image: zablose/php-fpm:${ZDI_VERSION_PHP}
        build:
            context: ./../../
            dockerfile: files/php-fpm.df
            args:
                - ARG_ENV=${ZDI_ENV}
                - ARG_TIMEZONE=${ZDI_TIMEZONE}
                - ARG_USER_GROUP_ID=${ZDI_USER_GROUP_ID}
                - ARG_USER_GROUP_NAME=${ZDI_USER_GROUP_NAME}
                - ARG_USER_ID=${ZDI_USER_ID}
                - ARG_USER_NAME=${ZDI_USER_NAME}
                - ARG_WEB_ROOT_DIR=${ZDI_WEB_ROOT_DIR}
        container_name: kanboard-php-fpm
        environment:
            ZDI_CONTAINER_NAME: kanboard-php-fpm
            ZDI_DB_HOSTNAME: kanboard-mariadb
        volumes:
            - ./.env:/home/${ZDI_USER_NAME}/.env
            - $HOME/.composer/cache/:/home/${ZDI_USER_NAME}/.composer/cache/
            - kanboard_web:${ZDI_WEB_ROOT_DIR}/
            - ./app/data/:${ZDI_WEB_ROOT_DIR}/data/
            - ./app/plugins/:${ZDI_WEB_ROOT_DIR}/plugins/
            - ./setup/php-fpm.sh:/home/${ZDI_USER_NAME}/post-setup.sh
        logging:
            driver: syslog
            options:
                syslog-address: 'tcp://127.0.0.1:514'
                tag: 'docker/kanboard-php-fpm'
        depends_on:
            - kanboard-mariadb
            - kanboard-rsyslog

    kanboard-mariadb:
        image: zablose/mariadb:10.11.6
        build:
            context: ./../../
            dockerfile: files/mariadb.df
            args:
                - ARG_ENV=${ZDI_ENV}
                - ARG_TIMEZONE=${ZDI_TIMEZONE}
                - ARG_USER_GROUP_ID=${ZDI_USER_GROUP_ID}
                - ARG_USER_GROUP_NAME=${ZDI_USER_GROUP_NAME}
                - ARG_USER_ID=${ZDI_USER_ID}
                - ARG_USER_NAME=${ZDI_USER_NAME}
        container_name: kanboard-mariadb
        environment:
            ZDI_CONTAINER_NAME: kanboard-mariadb
        logging:
            driver: syslog
            options:
                syslog-address: 'tcp://127.0.0.1:514'
                tag: 'docker/kanboard-mariadb'
        volumes:
            - ./.env:/home/${ZDI_USER_NAME}/.env
            - kanboard_db:/var/lib/mysql/
            - ./db/init/:/home/${ZDI_USER_NAME}/db_init/
            - ./setup/mariadb.sh:/home/${ZDI_USER_NAME}/post-setup.sh
        depends_on:
            - kanboard-rsyslog

    kanboard-rsyslog:
        image: zablose/rsyslog:3.19.1
        build:
            context: ./../../
            dockerfile: files/rsyslog.df
        container_name: kanboard-rsyslog
        ports:
            - '514:514'
        volumes:
            - ./logs/:/var/log/

volumes:
    kanboard_web:
    kanboard_db:
